CREATE TABLE coffee_type
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_enabled boolean NOT NULL,
    name character varying(255),
    price double precision NOT NULL
);
ALTER TABLE coffee_type
    ADD CONSTRAINT coffee_type_pkey PRIMARY KEY (id);
